### ISSUE TITLE
artifactory-push vs. artifactory-publisher

### ISSUE THREAD

**Issue by Voles** [beevelop/artifactory-push#8]
Hi,

First of all, thanks for your work! I appreciate the nice CLI tool, but I'm wondering what the advantage is of your module over the original [artifactory-publisher](https://www.npmjs.com/package/artifactory-publisher) module?

It seems like this module doesn't add any extra features to the original module?

Thanks in advance!

**Comment by beevelop** [comment]
Well, it seems as if @evil-shrike just recently got "inspired" by my little wrapper and decided to adapt it for his `artifactory-publisher`: https://github.com/CrocInc/artifactory-publisher/commit/ea6a8571f2bef992e7dbe04d1e89fc9bba881329

As his _adaption_ is pretty much identical there is no need to use `artifactory-push` anymore.

**Comment by evil-shrike** [comment]
@Voles @beevelop that's right. I added notes into README https://github.com/CrocInc/artifactory-publisher/commit/457e01ac96ea503ab2f8b97b84cb7eb715ef2cf3

**Comment by Voles** [comment]
@beevelop @evil-shrike thanks for the quick responses! However, I think a separate CLI module would be a nice separation of concerns.

artifactory-publisher could contain all artifactory logic, while artifactory-push (I suggest renaming to artifactory-publisher-cli) could contain all logic for a CLI tool.

WDYT?

**Comment by beevelop** [comment]
@Voles Actually having the same project acting as a library (for other Node.js projects) and as a command line tool is not quite uncommon.
So IMHO the best way forward would be to deprecate my `artifactory-push` implementation with a clear reference to `artifactory-publisher`. As CLI and library are very tightly coupled and the CLI implementation itself is just about 70 LOC, I would not recommend splitting them up – unless you, @Voles, think about additional features the CLI should support?

@evil-shrike Thanks for the credit. I will update this project with an official deprecation notice in the next release.
